/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.escom.relojmaestro;

/**
 *
 * @author emime
 */
public class InterfazReloj extends javax.swing.JFrame {

    /**
     * Creates new form InterfazReloj
     */
    public InterfazReloj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NameR1 = new javax.swing.JLabel();
        NameR2 = new javax.swing.JLabel();
        NameR3 = new javax.swing.JLabel();
        Reloj1 = new javax.swing.JLabel();
        Reloj2 = new javax.swing.JLabel();
        Reloj3 = new javax.swing.JLabel();
        BtnModifR1 = new javax.swing.JButton();
        BtnSendR1 = new javax.swing.JButton();
        BtnModifR2 = new javax.swing.JButton();
        BtnSendR2 = new javax.swing.JButton();
        BtnModifR3 = new javax.swing.JButton();
        BtnSendR3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Title.setText("Practica 2");

        NameR1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameR1.setText("Reloj 1");

        NameR2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameR2.setText("Reloj 2");

        NameR3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameR3.setText("Reloj 3");

        Reloj1.setText("00:00:00");

        Reloj2.setText("00:00:00");

        Reloj3.setText("00:00:00");

        BtnModifR1.setText("Modificar");

        BtnSendR1.setText("Enviar");

        BtnModifR2.setText("Modificar");

        BtnSendR2.setText("Enviar");

        BtnModifR3.setText("Modificar");

        BtnSendR3.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(205, 205, 205))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(NameR1)
                            .addGap(177, 177, 177)
                            .addComponent(NameR2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Reloj2)
                        .addGap(186, 186, 186)
                        .addComponent(Reloj3)
                        .addGap(275, 275, 275)))
                .addGap(18, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(BtnModifR1)
                .addGap(26, 26, 26)
                .addComponent(BtnSendR1)
                .addGap(70, 70, 70)
                .addComponent(BtnModifR2)
                .addGap(18, 18, 18)
                .addComponent(BtnSendR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(BtnModifR3)
                .addGap(37, 37, 37)
                .addComponent(BtnSendR3)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameR3)
                    .addComponent(Reloj1))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NameR1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NameR2)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reloj2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Reloj3)
                        .addComponent(NameR3)))
                .addGap(1, 1, 1)
                .addComponent(Reloj1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnSendR1)
                        .addComponent(BtnModifR1)
                        .addComponent(BtnModifR2)
                        .addComponent(BtnSendR2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnSendR3)
                        .addComponent(BtnModifR3)))
                .addGap(18, 142, Short.MAX_VALUE))
        );

        Reloj1.getAccessibleContext().setAccessibleName("jLabel3");
        Reloj3.getAccessibleContext().setAccessibleName("jLabel2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazReloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazReloj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModifR1;
    private javax.swing.JButton BtnModifR2;
    private javax.swing.JButton BtnModifR3;
    private javax.swing.JButton BtnSendR1;
    private javax.swing.JButton BtnSendR2;
    private javax.swing.JButton BtnSendR3;
    private javax.swing.JLabel NameR1;
    private javax.swing.JLabel NameR2;
    private javax.swing.JLabel NameR3;
    private javax.swing.JLabel Reloj1;
    private javax.swing.JLabel Reloj2;
    private javax.swing.JLabel Reloj3;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
